service:
  name: backend-service-test-dynamodb

frameworkVersion: '2'

custom:

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logs:
    restApi: true
    httpApi: true
  stackTags:
    Environment: ${self:provider.stage}
  deploymentBucket:
    name: 'pco-app-${self:provider.stage}.${self:provider.region}.deploy-files'
  lambdaHashingVersionen: 20201221
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:GetItem'
        - 'dynamodb:Query'
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/DeviceUser/*'
    #- ${file(./infra/role/role.yml)}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # Make sure AWS-SDK reuses HTTP connections
    DATA_STORE_ARN: datastore-${self:provider.stage}

functions:
  - ${file(./functions/get/function.yml)}



resources:
  ## DynamoDB
#  - ${file(./infra/dynamodb/single-table-data-store.yml)}

  ## S3
#  - ${file(./infra/s3/dynamic-assets-bucket.yml)}

  ## IAM
#  - ${file(./functions/api/rest/create/role.yml)}
#  - ${file(./functions/api/rest/get/role.yml)}
