service:
  name: backend-service-test-dynamodb

frameworkVersion: "2"

custom:
  stage: ${opt:stage, 'dev'} # Fallback to "local" if not set via --stage flag

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  logs:
    restApi: true
    httpApi: true
  stackTags:
    Environment: ${self:custom.stage}
  runtime: nodejs14.x
  #tracing: true # Enable X-Ray tracing
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # Make sure AWS-SDK reuses HTTP connections
    DATA_STORE_ARN: datastore-${self:provider.stage}

functions:
  # REST API
  - ${file(./functions/api/rest/get/function.yml)}
#  - ${file(./functions/api/rest/list/function.yml)} # TODO
#  - ${file(./functions/api/rest/create/function.yml)}
#  - ${file(./functions/api/rest/update/function.yml)} # TODO
#  - ${file(./functions/api/rest/delete/function.yml)}


resources:
  ## DynamoDB
#  - ${file(./infra/dynamodb/single-table-data-store.yml)}

  ## S3
#  - ${file(./infra/s3/dynamic-assets-bucket.yml)}

  ## IAM
#  - ${file(./functions/api/rest/create/role.yml)}
#  - ${file(./functions/api/rest/get/role.yml)}
